server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ural-contracts
    version: @project.version@
  datasource:
    url: ${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: false
        show_sql: ${SHOW_SQL}
        check_nullability: true
        hbm2ddl:
          auto: validate

  liquibase:
    enabled: true
    liquibase-schema: public
    database-change-log-table: ural_contracts_log
    database-change-log-lock-table: ural_contracts_lock
    change-log: classpath:db/changelog-master.xml
    default-schema: ural_contracts

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

contract-integrations:
  cars-url: ${CAR_URL}
  cargo-url: ${CARGO_URL}

graphhopper:
  base-url: ${GRAPHHOPPER_BASE_URL:https://graphhopper.com/api/1}
  api-key: ${GRAPHHOPPER_API_KEY:}
  profile: ${GRAPHHOPPER_PROFILE:car}
  locale: ${GRAPHHOPPER_LOCALE:ru}

kafka:
  notification-contract-topic:
    name: ${NOTIFICATION_CONTRACT_TOPIC_NAME}
    partitions: ${NOTIFICATION_CONTRACT_TOPIC_PARTITIONS}
  user-rating-topic:
    name: ${USER_RATING_TOPIC_NAME:ural-user-rating-topic}
    partitions: ${USER_RATING_TOPIC_PARTITIONS:1}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        tomcat:
          util: WARN
